name: Go

on:
  push:
    branches: [ main ]

jobs:

  test:
    name: Vet and Test
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Test Race Conditions
      run: go test -race -v ./...

    - name: Test Coverage
      run: go test -coverprofile=coverage.out ./...

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.out

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux]
        arch: [amd64]

    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      OUTPUT_BINARY: bootstrap
      OUTPUT_ZIP: function-${{ github.event.repository.name }}.zip

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Build
      run: |
        go build -o ${{ env.OUTPUT_BINARY }} -v .
        zip ${{ env.OUTPUT_ZIP }} ${{ env.OUTPUT_BINARY }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_ZIP }}
        path: ${{ env.OUTPUT_ZIP }}

    - name: Upload S3 Release Asset
      id: upload-s3-release-asset
      env:
        AWS_S3_BUCKET: releases.lab.dioad.net
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_UPLOAD_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_UPLOAD_S3_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
      run: |
        sha256sum ${{ env.OUTPUT_ZIP }} > ${{ env.OUTPUT_ZIP }}_SHA256SUMS
        aws s3 cp ${{ env.OUTPUT_ZIP }} s3://${{ env.AWS_S3_BUCKET }}/data/${{ github.event.repository.name }}/build/${{ env.OUTPUT_ZIP }} \
           --no-guess-mime-type \
           --content-type "application/zip" \
           --no-progress \
           --sse AES256
        aws s3 cp ${{ env.OUTPUT_ZIP }}_SHA256SUMS s3://${{ env.AWS_S3_BUCKET }}/data/${{ github.event.repository.name }}/build/${{ env.OUTPUT_ZIP }}_SHA256SUMS \
           --no-guess-mime-type \
           --content-type "text/plain" \
           --no-progress \
           --sse AES256
