name: Go

on:
  push:
    branches: [ master ]

jobs:

  test:
    name: Vet and Test
    runs-on: ubuntu-20.04

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Configure github token
      env:
        TOKEN_USER: ${{ secrets.WORKFLOW_TOKEN_USER }}
        TOKEN: ${{ secrets.WORKFLOW_TOKEN}}
      run: |
        git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        git config -l --global
        go get -v -t -d ./...

    - name: Vet
      run: |
        go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Test Race Conditions
      run: go test -race -v ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        os: [darwin, linux, windows]
        arch: [amd64]
        include:
        - os: linux
          arch: arm64
        - os: darwin
          arch: arm64

    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Configure github token
      env:
        TOKEN_USER: ${{ secrets.WORKFLOW_TOKEN_USER }}
        TOKEN: ${{ secrets.WORKFLOW_TOKEN}}
      run: |
        git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        git config -l --global
        go get -v -t -d ./...

    - name: Build
      run: |
        go build -o ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }} -v .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}
        path: ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }}

    - name: Upload S3 Release Asset
      id: upload-s3-release-asset
      env:
        AWS_S3_BUCKET: dioad-labs-artifacts
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_UPLOAD_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_UPLOAD_S3_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
      run: |
        aws s3 cp ${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }} s3://${{ env.AWS_S3_BUCKET }}/${{ github.event.repository.name }}/build/${{ github.event.repository.name }}_${{ matrix.os }}_${{ matrix.arch }} \
           --no-guess-mime-type \
           --content-type "application/octet-stream" \
           --no-progress \
           --sse AES256

