name: Go Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Vet and Test
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Test Race Conditions
      run: go test -race -v ./...

    - name: Test Coverage
      run: go test -coverprofile=coverage.out ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux]
        arch: [amd64]

    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true

    - name: Build
      run: go build -v .

